sonar.projectKey=ianosei8_king-of-the-hill
sonar.organization=ianosei8

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.exclusions=src/app/favicon.ico
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
